service: hms-email-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    GMAIL_USER: ${env:GMAIL_USER}
    GMAIL_PASSWORD: ${env:GMAIL_PASSWORD}

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline
