# Generated by Django 4.2.7 on 2026-01-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='availability.doctoravailability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
